### ISSUE TITLE
Improve content after changing order of sections

### ISSUE THREAD

**Issue by MagdaPaj** [observability-lab-cse/observability-lab#120]
After updating the order of sections (moving custom metrics from section 7 to section 4) there should be more adjustments to the content:
- the end of section 03 refers to visualizations of section 04, but now there is no visualizations
- now custom metrics (section 04) has visualization part, but it should probably be moved later, as now it's because the Visualization section

**Comment by MaggieSalak** [comment]
@MagdaPaj It's true that the metrics section has a section about visualizing the metrics. However, I'm a bit concerned that splitting this section and moving the 'visualization' part out of it will make the journey more confusing. I'm not sure what's the best way to deal with this, let's discuss next time we meet.
